# Generated by Django 5.0.4 on 2024-05-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InformationsCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('carrera', models.CharField(max_length=200)),
                ('celular', models.CharField(max_length=200)),
            ],
        ),
    ]
